/**
 * drift setup — first-time interactive wizard.
 *
 * Creates drift.toml with sensible defaults and initializes drift.db.
 */

import type { Command } from 'commander';
import { loadNapi } from '../napi.js';
import * as fs from 'node:fs';
import * as path from 'node:path';

/** Default drift.toml content. */
const DEFAULT_DRIFT_TOML = `# Drift configuration
# Generated by drift setup

[scan]
include = ["src/**", "lib/**", "app/**"]
exclude = ["node_modules/**", "dist/**", "build/**", ".git/**", "vendor/**"]

[policy]
mode = "standard"  # strict | standard | lenient

[gates]
pattern-compliance = { enabled = true, threshold = 80 }
constraint-verification = { enabled = true }
security-boundaries = { enabled = true }
test-coverage = { enabled = true, threshold = 60 }
error-handling = { enabled = true }
regression = { enabled = true }

[reporters]
formats = ["console", "json"]
`;

export function registerSetupCommand(program: Command): void {
  program
    .command('setup')
    .description('Initialize Drift in the current project — creates drift.toml and drift.db')
    .option('--force', 'Overwrite existing configuration')
    .action(async (opts: { force?: boolean }) => {
      const projectRoot = process.cwd();
      const configPath = path.join(projectRoot, 'drift.toml');
      const driftDir = path.join(projectRoot, '.drift');

      try {
        // Check for existing config
        if (fs.existsSync(configPath) && !opts.force) {
          process.stdout.write(
            'drift.toml already exists. Use --force to overwrite.\n',
          );
          process.exitCode = 0;
          return;
        }

        // Create .drift directory
        if (!fs.existsSync(driftDir)) {
          fs.mkdirSync(driftDir, { recursive: true });
        }

        // Write drift.toml
        fs.writeFileSync(configPath, DEFAULT_DRIFT_TOML, 'utf-8');
        process.stdout.write(`Created ${configPath}\n`);

        // Initialize NAPI (creates drift.db)
        const napi = loadNapi();
        napi.drift_init({ projectRoot });
        process.stdout.write(`Initialized drift.db in ${driftDir}\n`);

        process.stdout.write('\nDrift is ready! Run `drift scan` to analyze your project.\n');
        process.exitCode = 0;
      } catch (err) {
        process.stderr.write(`Error: ${err instanceof Error ? err.message : err}\n`);
        process.exitCode = 2;
      }
    });
}
